# Generated by Django 5.0.7 on 2024-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('shop', models.CharField(max_length=122)),
                ('other', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('reference', models.TextField()),
                ('amount', models.IntegerField()),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('pin', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('descr', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
