# Generated by Django 5.0.7 on 2024-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='other',
            field=models.CharField(max_length=150),
        ),
    ]
